export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_RECONCILIATION: 'VIEW_RECONCILIATION',
  MANUAL_RECONCILIATION: 'MANUAL_RECONCILIATION',
  REPORT_DIVERGENCE: 'REPORT_DIVERGENCE',
  APPROVE_RECONCILIATION: 'APPROVE_RECONCILIATION',
  UPLOAD_STATEMENT: 'UPLOAD_STATEMENT',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_CATEGORIES: 'MANAGE_CATEGORIES',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  GENERATE_REPORTS: 'GENERATE_REPORTS',
  RETROACTIVE_ENTRY: 'RETROACTIVE_ENTRY',
};
