export const RECONCILIATION_STATUS = {
  OPEN: 'OPEN',
  IN_REVIEW: 'IN_REVIEW',
  APPROVED: 'APPROVED',
  CLOSED: 'CLOSED',
};

export const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  RECONCILED: 'RECONCILED',
  IGNORED: 'IGNORED',
  DIVERGENCE: 'DIVERGENCE',
};

export const MATCH_TYPE = {
  AUTO: 'AUTO',
  MANUAL: 'MANUAL',
  PENDING: 'PENDING',
};
